package aplicacion.modelo.dominio;
// Generated 10-jun-2019 2:25:41 by Hibernate Tools 4.3.1


import aplicacion.modelo.dominio.ModoPago;
import aplicacion.modelo.dominio.Usuario;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int numFactura;
     private ModoPago modopago;
     private Usuario usuarios;
     private Date fecha;
     private Set detalles = new HashSet(0);

    public Factura() {
    }

	
    public Factura(int numFactura, ModoPago modopago, Usuario usuarios) {
        this.numFactura = numFactura;
        this.modopago = modopago;
        this.usuarios = usuarios;
    }
    public Factura(int numFactura, ModoPago modopago, Usuario usuarios, Date fecha, Set detalles) {
       this.numFactura = numFactura;
       this.modopago = modopago;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.detalles = detalles;
    }
   
    public int getNumFactura() {
        return this.numFactura;
    }
    
    public void setNumFactura(int numFactura) {
        this.numFactura = numFactura;
    }
    public ModoPago getModopago() {
        return this.modopago;
    }
    
    public void setModopago(ModoPago modopago) {
        this.modopago = modopago;
    }
    public Usuario getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuario usuarios) {
        this.usuarios = usuarios;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


