package aplicacion.modelo.dominio;
// Generated 03/06/2019 23:37:11 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int codigo;
     private String nombreUsuario;
     private String password;
     private String tipoUsuario;
     private String apellidos;
     private String nombres;
     private Boolean estado;

    public Usuario() {
    }

	
    public Usuario(int codigo) {
        this.codigo = codigo;
    }
    public Usuario(int codigo, String nombreUsuario, String password, String tipoUsuario, String apellidos, String nombres, Boolean estado) {
       this.codigo = codigo;
       this.nombreUsuario = nombreUsuario;
       this.password = password;
       this.tipoUsuario = tipoUsuario;
       this.apellidos = apellidos;
       this.nombres = nombres;
       this.estado = estado;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }




}


